"use client"
import { useEffect, useMemo, useState } from "react"
import useSWR from "swr"
import { Area, AreaChart, CartesianGrid, Line, XAxis, YAxis } from "recharts"
import { Activity, Bell, Bot, Check, ExternalLink, Newspaper, RefreshCw, Search, ShieldCheck, Star, TrendingDown, TrendingUp, Zap } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import type { Signal } from "@/lib/indicators"

const macro=["XU100","XU030","SP500","NASDAQ","DJI","USDTRY","EURTRY","XAUUSD","BRENT"]
const chartConfig={price:{label:"Fiyat",color:"var(--chart-1)"},sma:{label:"HO 20",color:"var(--chart-2)"}} satisfies ChartConfig
const fetcher=(url:string)=>fetch(url).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);return p})
const fmt=(v?:number)=>Number.isFinite(v)?v!.toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:2}):"—"
type Asset={symbol:string;name:string;market:"BIST"|"ABD"};type Quote={symbol:string;name:string;price?:number;change?:number;ok:boolean};type News={title:string;source:string;url?:string;publishedAt?:string};type Advice={key:string;label:string;signal:Signal;confidence:number;action:string;invalidation:number;target:number};type Analyst={rating?:string;score?:number;targetLow?:number;targetMean?:number;targetHigh?:number;analystCount?:number};type Data={symbol:string;name:string;market:string;currency:string;price:number;change:number;updatedAt:string;source:string;technical:{signal:Signal;confidence:number;support:number;resistance:number;values:Record<string,number>;fibonacci:Record<string,number>;chart:{date:string;price:number;sma:number}[]};advice:Advice[];news:News[];analyst?:Analyst}
type View="terminal"|"automation"|"news";type Rules={support:boolean;resistance:boolean;signal:boolean;news:boolean}
function Change({value=0}:{value?:number}){return <span className={cn("inline-flex items-center gap-1 font-mono text-xs font-semibold",value>=0?"text-positive":"text-negative")}>{value>=0?<TrendingUp/>:<TrendingDown/>}{value>=0?"+":""}{fmt(value)}%</span>}
function SignalBadge({signal}:{signal:Signal}){return <Badge variant="outline" className={cn("font-mono",signal.includes("AL")?"border-positive/40 bg-positive/10 text-positive":signal.includes("SAT")?"border-negative/40 bg-negative/10 text-negative":"border-warning/40 bg-warning/10 text-warning")}>{signal}</Badge>}
function Ticker({quotes}:{quotes:Quote[]}){return <div className="ticker-shell"><div className="ticker-track">{[...quotes,...quotes].map((q,i)=><div className="flex shrink-0 items-center gap-3 px-5" key={`${q.symbol}-${i}`}><span className="text-xs text-muted-foreground">{q.name}</span><span className="font-mono text-xs font-bold">{fmt(q.price)}</span>{q.ok?<Change value={q.change}/>:<span className="text-xs text-negative">Veri yok</span>}</div>)}</div></div>}
function Nav({view,setView}:{view:View;setView:(v:View)=>void}){return <div className="flex gap-1">{([{v:"terminal",t:"Terminal",i:Activity},{v:"automation",t:"Otomasyon",i:Zap},{v:"news",t:"Haberler",i:Newspaper}] as const).map(x=><Button key={x.v} size="sm" variant={view===x.v?"default":"ghost"} onClick={()=>setView(x.v)}><x.i/>{x.t}</Button>)}</div>}
export function FinanceDashboard(){
 const[selected,setSelected]=useState("TUPRS"),[query,setQuery]=useState(""),[market,setMarket]=useState<"Tümü"|"BIST"|"ABD">("Tümü"),[favorites,setFavorites]=useState<string[]>([]),[view,setView]=useState<View>("terminal"),[capital,setCapital]=useState("100000"),[risk,setRisk]=useState("1"),[rules,setRules]=useState<Rules>({support:true,resistance:true,signal:true,news:true})
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem("piyasaiq:favorites:v1")??"[]"));const r=JSON.parse(localStorage.getItem("piyasaiq:rules:v2")??"null");if(r)setRules(r)}catch{}},[])
 const{data:catalog}=useSWR<{assets:Asset[]}>("/api/market?catalog=1",fetcher),{data,error,isLoading,mutate}=useSWR<Data>(`/api/market?symbol=${selected}`,fetcher,{refreshInterval:300000,keepPreviousData:true}),{data:globalNews}=useSWR<{news:News[]}>(view==="news"?"/api/market?news=1":null,fetcher,{refreshInterval:300000})
 const{data:quotePayload}=useSWR("macro-quotes",()=>fetch("/api/market",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:macro})}).then(r=>r.json()),{refreshInterval:300000});const quotes:Quote[]=quotePayload?.data??macro.map(symbol=>({symbol,name:symbol,ok:false}))
 const assets=useMemo(()=>{const q=query.toLocaleLowerCase("tr-TR");return(catalog?.assets??[]).filter(a=>(market==="Tümü"||a.market===market)&&`${a.symbol} ${a.name}`.toLocaleLowerCase("tr-TR").includes(q)).sort((a,b)=>Number(favorites.includes(b.symbol))-Number(favorites.includes(a.symbol)))},[catalog,query,market,favorites])
 const autoBody=useMemo(()=>data?JSON.stringify({symbol:data.symbol,market:{...data,macro:quotes.filter(q=>q.ok)},question:`${data.symbol} için şirket odaklı otomatik analiz üret. İndikatör sinyalini tekrar etmek yerine şirketi etkileyen emtia, kur, endeks, bilanço ve haber başlıklarının olası etkisini açıkla. Verilmeyen bilanço verisini uydurma; hangi verinin ayrıca kontrol edilmesi gerektiğini söyle.`}):null,[data,quotes])
 const{data:autoAI,isLoading:aiLoading,mutate:refreshAI}=useSWR<{text:string;source:string}>(data?["auto-analysis",data.symbol,data.updatedAt]:null,()=>fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:autoBody!}).then(r=>r.json()),{revalidateOnFocus:false})
 function favorite(s:string){setFavorites(c=>{const n=c.includes(s)?c.filter(x=>x!==s):[s,...c];localStorage.setItem("piyasaiq:favorites:v1",JSON.stringify(n));return n})}function rule(k:keyof Rules){setRules(c=>{const n={...c,[k]:!c[k]};localStorage.setItem("piyasaiq:rules:v2",JSON.stringify(n));return n})}
 const riskAmount=Number(capital)*Number(risk)/100,stopDistance=data?Math.max(data.price-data.technical.support,data.technical.values.atr,0):0,units=stopDistance?Math.floor(riskAmount/stopDistance):0
 return <main className="min-h-screen bg-background font-sans"><Ticker quotes={quotes}/><header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="flex min-h-14 flex-wrap items-center gap-2 px-3 lg:px-5"><div className="mr-2 flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><Activity/></div><b className="text-sm">PİYASA<span className="text-primary">IQ</span></b></div><Nav view={view} setView={setView}/><div className="relative ml-auto hidden w-48 md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-8 pl-9" placeholder="Hisse veya sembol ara"/></div><Button size="icon" variant="ghost" aria-label="Bildirimler"><Bell/></Button></div></header>
 <div className="finance-grid flex flex-col gap-3 p-3 lg:p-4">
 {view==="news"?<NewsCenter news={globalNews?.news??[]} quotes={quotes} onBack={()=>setView("terminal")}/>:view==="automation"?<Automation data={data} rules={rules} toggle={rule} capital={capital} setCapital={setCapital} risk={risk} setRisk={setRisk} riskAmount={riskAmount} units={units} onBack={()=>setView("terminal")}/>:<>
 <section className="grid gap-3 min-[820px]:grid-cols-[230px_minmax(0,1fr)]"><Card size="sm"><CardHeader className="border-b"><CardTitle>Piyasalar</CardTitle><CardDescription>BIST ve ABD · favoriler üstte</CardDescription><div className="flex gap-1 pt-2">{(["Tümü","BIST","ABD"] as const).map(x=><Button key={x} size="sm" variant={market===x?"secondary":"ghost"} onClick={()=>setMarket(x)}>{x}</Button>)}</div><div className="relative mt-2 md:hidden"><Search className="absolute left-3 top-1/2 -translate-y-1/2"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ara"/></div></CardHeader><CardContent className="flex max-h-[390px] flex-col overflow-y-auto px-0">{assets.map(a=><div key={a.symbol} className={cn("flex items-center border-b",selected===a.symbol&&"bg-primary/8")}><button className="p-3" aria-label={`${a.symbol} favori`} onClick={()=>favorite(a.symbol)}><Star className={cn(favorites.includes(a.symbol)&&"fill-warning text-warning")}/></button><button className="min-w-0 flex-1 py-2 pr-3 text-left" onClick={()=>setSelected(a.symbol)}><div className="flex justify-between"><b className="font-mono text-xs">{a.symbol}</b><Badge variant="outline">{a.market}</Badge></div><p className="truncate text-xs text-muted-foreground">{a.name}</p></button></div>)}</CardContent></Card>
 <Card size="sm"><CardHeader><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><CardTitle className="font-mono text-lg">{data?.symbol??selected}</CardTitle>{data&&<SignalBadge signal={data.technical.signal}/>}</div><CardDescription>{data?.name??"Yükleniyor"} · Yahoo Finance gecikmeli</CardDescription></div><div className="text-right"><b className="font-mono text-xl">{data?.currency==="TRY"?"TL ":"$"}{fmt(data?.price)}</b>{data&&<Change value={data.change}/>}</div></div></CardHeader><CardContent>{error?<p className="py-20 text-center text-negative">Veri alınamadı: {error.message}</p>:isLoading||!data?<p className="py-20 text-center text-muted-foreground">Güncel veri yükleniyor…</p>:<><ChartContainer config={chartConfig} className="h-[200px] w-full aspect-auto"><AreaChart data={data.technical.chart}><CartesianGrid vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false} minTickGap={25}/><YAxis orientation="right" domain={["dataMin - 2","dataMax + 2"]} width={45}/><ChartTooltip content={<ChartTooltipContent/>}/><Area dataKey="price" type="monotone" stroke="var(--color-price)" fill="var(--color-price)" fillOpacity={.1}/><Line dataKey="sma" type="monotone" stroke="var(--color-sma)" dot={false}/></AreaChart></ChartContainer><div className="flex flex-wrap items-center gap-2 rounded-md border bg-muted/30 p-2"><b className="text-xs">Genel indikatör</b><SignalBadge signal={data.technical.signal}/><span className="font-mono text-xs">%{data.technical.confidence} güven</span><span className="ml-auto text-xs text-muted-foreground">Destek {fmt(data.technical.support)} · Direnç {fmt(data.technical.resistance)}</span></div></>}</CardContent></Card></section>
 {data&&<section className="grid gap-3 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]"><Card size="sm" className="border-ai/40 bg-ai-surface"><CardHeader><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><Bot className="text-ai"/><CardTitle>Claude Şirket Analizi</CardTitle></div><CardDescription>Haber, emtia, kur ve şirket etkileri · sinyal tekrarı değil</CardDescription></div><Button size="sm" variant="outline" onClick={()=>refreshAI()}><RefreshCw/>Yenile</Button></div></CardHeader><CardContent><p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{aiLoading?"Claude şirketi etkileyen güncel verileri değerlendiriyor…":autoAI?.text??"Analiz hazırlanamadı."}</p><p className="mt-3 text-[10px] text-muted-foreground">Kaynak: Yahoo Finance · Model: Claude · Eksik bilanço verisi uydurulmaz · Yatırım tavsiyesi değildir.</p></CardContent></Card><div className="flex flex-col gap-3"><ForecastCard data={data}/><AnalystCard data={data}/></div></section>}
 </>}
 </div></main>
}
function NewsItem({news}:{news:News}){return <a href={news.url} target="_blank" rel="noreferrer" className="flex items-start justify-between gap-3 rounded-lg border bg-card p-3 hover:border-primary/40"><div><p className="text-sm font-medium">{news.title}</p><p className="mt-1 text-xs text-muted-foreground">{news.source}{news.publishedAt?` · ${new Date(news.publishedAt).toLocaleString("tr-TR")}`:""}</p></div><ExternalLink className="shrink-0"/></a>}
function NewsCenter({news,quotes,onBack}:{news:News[];quotes:Quote[];onBack:()=>void}){const featured=quotes.filter(q=>["BRENT","XAUUSD","USDTRY","XU100","SP500"].includes(q.symbol));return <section className="mx-auto w-full max-w-5xl"><div className="mb-4 flex items-center justify-between"><div><h1 className="text-xl font-bold">Piyasa Haber Merkezi</h1><p className="text-sm text-muted-foreground">Emtia, kur ve endeks bağlamıyla kaynaklı haber akışı</p></div><Button variant="outline" onClick={onBack}>Terminale dön</Button></div><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{featured.map(q=><Card key={q.symbol} size="sm" className={cn(q.symbol==="BRENT"&&"border-warning/40 bg-warning/5")}><CardHeader><CardDescription>{q.name}</CardDescription><CardTitle className="font-mono">{fmt(q.price)}</CardTitle><Change value={q.change}/></CardHeader></Card>)}</div><Card size="sm" className="mb-4 border-ai/30 bg-ai-surface"><CardContent className="flex items-start gap-3 p-4"><ShieldCheck className="shrink-0 text-ai"/><div><b className="text-sm">Bugünün bağlam kontrolü</b><p className="text-xs leading-relaxed text-muted-foreground">Haber başlığını tek başına sinyal sayma. Brent, kur ve endeks hareketi aynı yönde teyit veriyorsa şirket etkisi güçlenir; aksi durumda pozisyon boyutunu küçült.</p></div></CardContent></Card><div className="grid gap-3 md:grid-cols-2">{news.length?news.map(n=><NewsItem key={n.url??n.title} news={n}/>):<p className="text-muted-foreground">Haberler yükleniyor…</p>}</div></section>}
function Automation({data,rules,toggle,capital,setCapital,risk,setRisk,riskAmount,units,onBack}:{data?:Data;rules:Rules;toggle:(k:keyof Rules)=>void;capital:string;setCapital:(v:string)=>void;risk:string;setRisk:(v:string)=>void;riskAmount:number;units:number;onBack:()=>void}){return <section className="mx-auto w-full max-w-5xl"><div className="mb-4 flex justify-between"><div><h1 className="text-xl font-bold">Otomasyon Merkezi</h1><p className="text-sm text-muted-foreground">Vade planları, alarm, risk ve disiplin paneli · emir göndermez</p></div><Button variant="outline" onClick={onBack}>Terminale dön</Button></div>{data&&<div className="mb-3 grid gap-3 md:grid-cols-3">{data.advice.map(a=><Card key={a.key} size="sm" className="border-primary/20"><CardHeader><div className="flex justify-between"><div><CardDescription>{a.label} plan</CardDescription><CardTitle>Ne yapmalı?</CardTitle></div><SignalBadge signal={a.signal}/></div></CardHeader><CardContent><p className="text-sm">{a.action}</p><p className="mt-2 font-mono text-xs text-muted-foreground">Risk {fmt(a.invalidation)} · Hedef {fmt(a.target)}</p></CardContent></Card>)}</div>}<div className="grid gap-3 md:grid-cols-2"><Card><CardHeader><CardTitle>Aktif kurallar</CardTitle><CardDescription>{data?.symbol} için tarayıcıda saklanır</CardDescription></CardHeader><CardContent className="grid gap-2">{([{k:"support",t:"Destek kırılımı alarmı"},{k:"resistance",t:"Direnç teyidi alarmı"},{k:"signal",t:"Sinyal değişimi"},{k:"news",t:"Önemli haber bildirimi"}] as const).map(x=><button key={x.k} onClick={()=>toggle(x.k)} className={cn("flex items-center justify-between rounded-lg border p-3 text-left",rules[x.k]&&"border-primary/50 bg-primary/8")}><span>{x.t}</span>{rules[x.k]&&<Check className="text-primary"/>}</button>)}</CardContent></Card><Card><CardHeader><CardTitle>Risk bazlı pozisyon boyutu</CardTitle><CardDescription>Kâr vaadi değil; tek işlemde kaybı sınırlama aracı</CardDescription></CardHeader><CardContent className="grid gap-3"><label className="text-sm">Portföy (TL)<Input type="number" value={capital} onChange={e=>setCapital(e.target.value)}/></label><label className="text-sm">İşlem başına risk (%)<Input type="number" min="0.1" max="5" step="0.1" value={risk} onChange={e=>setRisk(e.target.value)}/></label><div className="rounded-lg border bg-muted/30 p-3"><p className="text-xs text-muted-foreground">Azami planlanan risk</p><b className="font-mono">TL {fmt(riskAmount)}</b><p className="mt-2 text-xs text-muted-foreground">Destek/ATR mesafesine göre yaklaşık adet</p><b className="font-mono">{units} adet</b></div><p className="text-xs text-warning"><ShieldCheck className="mr-1 inline"/>Likidite, komisyon ve fiyat boşlukları gerçek zararı artırabilir.</p></CardContent></Card></div></section>}
function AnalystCard({data}:{data:Data}){const a=data.analyst;return <Card size="sm"><CardHeader><CardTitle>Analist görünümü</CardTitle><CardDescription>Yahoo Finance tarafından sunulursa gösterilir</CardDescription></CardHeader><CardContent>{a?.targetMean?<div className="grid grid-cols-3 gap-2"><div><p className="text-xs text-muted-foreground">Konsensüs</p><b className="uppercase">{a.rating??"—"}</b></div><div><p className="text-xs text-muted-foreground">Hedef fiyat</p><b className="font-mono">{fmt(a.targetMean)}</b></div><div><p className="text-xs text-muted-foreground">Analist</p><b>{a.analystCount??"—"}</b></div></div>:<p className="text-sm text-muted-foreground">Bu sembol için doğrulanabilir analist hedefi bulunamadı; tahmin uydurulmadı.</p>}</CardContent></Card>}
function ForecastCard({data}:{data:Data}){const atr=data.technical.values.atr||0;const fib=data.technical.fibonacci;const upside=Math.max(data.technical.resistance,fib.level236||0,data.price+atr);const downside=Math.min(data.technical.support,fib.level618||data.price,data.price-atr);const upPct=((upside/data.price)-1)*100;const downPct=((downside/data.price)-1)*100;return <Card size="sm" className="border-primary/30 bg-primary/5"><CardHeader><CardTitle>Tahmini hareket alanı</CardTitle><CardDescription>Teknik seviyeler + ATR + Fibonacci kesişimi</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3"><div className="rounded-md border border-positive/30 bg-positive/10 p-3"><p className="text-xs text-muted-foreground">Yukarı senaryo</p><b className="font-mono text-lg text-positive">{fmt(upside)}</b><p className="font-mono text-xs text-positive">{upPct>=0?"+":""}{fmt(upPct)}%</p></div><div className="rounded-md border border-negative/30 bg-negative/10 p-3"><p className="text-xs text-muted-foreground">Aşağı risk</p><b className="font-mono text-lg text-negative">{fmt(downside)}</b><p className="font-mono text-xs text-negative">{fmt(downPct)}%</p></div><p className="col-span-2 text-[10px] leading-relaxed text-muted-foreground">Bunlar kesin fiyat tahmini değil, mevcut oynaklık ve teknik kesişimlerden üretilen senaryo sınırlarıdır.</p></CardContent></Card>}
