// Comprehensive Borsa İstanbul (BIST) equity universe.
// key = BIST ticker, value = company short name. Yahoo symbol is `${key}.IS`.
export const bistStocks: Record<string, string> = {
  ACSEL: "Acıselsan Acıpayam Selüloz",
  ADEL: "Adel Kalemcilik",
  ADESE: "Adese AVM",
  ADGYO: "Adra Gayrimenkul YO",
  AEFES: "Anadolu Efes",
  AFYON: "Afyon Çimento",
  AGESA: "Agesa Hayat ve Emeklilik",
  AGHOL: "AG Anadolu Grubu Holding",
  AGROT: "Agrotech Yüksek Teknoloji",
  AGYO: "Atakule Gayrimenkul YO",
  AHGAZ: "Ahlatcı Doğal Gaz",
  AKBNK: "Akbank",
  AKCNS: "Akçansa",
  AKENR: "Akenerji",
  AKFGY: "Akfen Gayrimenkul YO",
  AKFYE: "Akfen Yenilenebilir Enerji",
  AKGRT: "Aksigorta",
  AKMGY: "Akmerkez Gayrimenkul YO",
  AKSA: "Aksa Akrilik",
  AKSEN: "Aksa Enerji",
  AKSGY: "Akiş Gayrimenkul YO",
  AKSUE: "Aksu Enerji",
  AKYHO: "Akdeniz Yatırım Holding",
  ALARK: "Alarko Holding",
  ALBRK: "Albaraka Türk",
  ALCAR: "Alarko Carrier",
  ALCTL: "Alcatel Lucent Teletaş",
  ALFAS: "Alfa Solar Enerji",
  ALGYO: "Alarko Gayrimenkul YO",
  ALKA: "Alkim Kağıt",
  ALKIM: "Alkim Kimya",
  ALMAD: "Altınyağ Madencilik",
  ALTINS1: "Altınkılıç Gıda",
  ALVES: "Alves Kablo",
  ANELE: "Anel Elektrik",
  ANGEN: "Anatolia Tanı ve Biyoteknoloji",
  ANHYT: "Anadolu Hayat Emeklilik",
  ANSGR: "Anadolu Sigorta",
  ARASE: "Aras Elektrik Dağıtım",
  ARCLK: "Arçelik",
  ARDYZ: "ARD Grup Bilişim",
  ARENA: "Arena Bilgisayar",
  ARSAN: "Arsan Tekstil",
  ARZUM: "Arzum",
  ASELS: "Aselsan",
  ASGYO: "Aslan Gayrimenkul YO",
  ASTOR: "Astor Enerji",
  ASUZU: "Anadolu Isuzu",
  ATAGY: "Ata Gayrimenkul YO",
  ATAKP: "Atakey Patates",
  ATATP: "ATP Ticari Bilgisayar",
  ATEKS: "Akın Tekstil",
  ATLAS: "Atlas Menkul Kıymetler YO",
  ATSYH: "Atlantis Yatırım Holding",
  AVGYO: "Avrasya Gayrimenkul YO",
  AVHOL: "Avrupakent GYO",
  AVOD: "A.V.O.D. Gıda",
  AVPGY: "Avrupa Yakası Gayrimenkul",
  AVTUR: "Avrasya Petrol ve Turistik",
  AYCES: "Altınyunus Çeşme",
  AYDEM: "Aydem Yenilenebilir Enerji",
  AYEN: "Ayen Enerji",
  AYES: "Ayes Çelik Hasır",
  AYGAZ: "Aygaz",
  AZTEK: "Aztek Teknoloji",
  BAGFS: "Bagfaş",
  BAKAB: "Bak Ambalaj",
  BALAT: "Balatacılar Balatacılık",
  BANVT: "Banvit",
  BARMA: "Baraka Fintech",
  BASCM: "Baştaş Çimento",
  BASGZ: "Başkent Doğalgaz",
  BAYRK: "Bayrak EBT",
  BERA: "Bera Holding",
  BEYAZ: "Beyaz Filo",
  BFREN: "Bosch Fren Sistemleri",
  BIENY: "Bien Yapı Ürünleri",
  BIGCH: "Bigchefs",
  BIMAS: "BİM Birleşik Mağazalar",
  BINHO: "Binho Holding",
  BIOEN: "Biotrend Enerji",
  BIZIM: "Bizim Toptan",
  BJKAS: "Beşiktaş Futbol",
  BLCYT: "Bilici Yatırım",
  BMSCH: "BMS Çelik Hasır",
  BMSTL: "BMS Birleşik Metal",
  BNTAS: "Bantaş Ambalaj",
  BOBET: "Bosphorus Gayrimenkul",
  BORLS: "Borlease Otomotiv",
  BORSK: "Borusan Yatırım",
  BOSSA: "Bossa Ticaret",
  BRISA: "Brisa",
  BRKSN: "Berkosan Yalıtım",
  BRKVY: "Birikim Varlık Yönetim",
  BRLSM: "Birleşim Mühendislik",
  BRMEN: "Birlik Mensucat",
  BRSAN: "Borusan Boru",
  BRYAT: "Borusan Yatırım Pazarlama",
  BSOKE: "Batısöke Çimento",
  BTCIM: "Batı Çimento",
  BUCIM: "Bursa Çimento",
  BURCE: "Burçelik",
  BURVA: "Burçelik Vana",
  BVSAN: "Bilecik Vana",
  CANTE: "Çan2 Termik",
  CASA: "Casa Emtia Petrol",
  CATES: "Çates Elektrik",
  CCOLA: "Coca-Cola İçecek",
  CELHA: "Çelik Halat",
  CEMAS: "Çemaş Döküm",
  CEMTS: "Çemtaş",
  CEOEM: "CEO Event Medya",
  CIMSA: "Çimsa",
  CLEBI: "Çelebi Hava Servisi",
  CMBTN: "Çimbeton",
  CMENT: "Çimentaş",
  CONSE: "Consus Enerji",
  COSMO: "Cosmos Yatırım Holding",
  CRDFA: "Creditwest Faktoring",
  CRFSA: "CarrefourSA",
  CUSAN: "Çuhadaroğlu Metal",
  CVKMD: "CVK Maden İşletmeleri",
  CWENE: "CW Enerji",
  DAGHL: "Dağı Yatırım Holding",
  DAGI: "Dagi Giyim",
  DAPGM: "DAP Gayrimenkul",
  DARDL: "Dardanel",
  DENGE: "Denge Yatırım Holding",
  DERHL: "Derlüks Deri",
  DERIM: "Derimod",
  DESA: "Desa Deri",
  DESPC: "Despec Bilgisayar",
  DEVA: "Deva Holding",
  DGATE: "Datagate Bilgisayar",
  DGGYO: "Doğuş Gayrimenkul YO",
  DGNMO: "Doğanlar Mobilya",
  DIRIT: "Diriteks Diriliş Tekstil",
  DITAS: "Ditaş Doğan",
  DMSAS: "Demisaş Döküm",
  DNISI: "Dinamik Isı Makine",
  DOAS: "Doğuş Otomotiv",
  DOBUR: "Doğan Burda",
  DOCO: "DO & CO",
  DOFER: "Dofer Yapı",
  DOGUB: "Doğusan",
  DOHOL: "Doğan Holding",
  DOKTA: "Döktaş Dökümcülük",
  DURDO: "Duran Doğan Basım",
  DYOBY: "DYO Boya",
  DZGYO: "Deniz Gayrimenkul YO",
  EBEBK: "ebebek",
  ECILC: "EİS Eczacıbaşı İlaç",
  ECZYT: "Eczacıbaşı Yatırım",
  EDATA: "E-Data Teknoloji",
  EDIP: "Edip Gayrimenkul",
  EGEEN: "Ege Endüstri",
  EGEPO: "Ege Profil",
  EGGUB: "Ege Gübre",
  EGPRO: "Ege Profil Ticaret",
  EGSER: "Ege Seramik",
  EKGYO: "Emlak Konut GYO",
  EKIZ: "Ekiz Kimya",
  EKSUN: "Eksun Gıda",
  ELITE: "Elite Naturel Organik",
  EMKEL: "Emek Elektrik",
  EMNIS: "Eminiş Ambalaj",
  ENERY: "Enerya Enerji",
  ENJSA: "Enerjisa Enerji",
  ENKAI: "Enka İnşaat",
  ENSRI: "Ensari Deri Gıda",
  ENTRA: "Entra Enerji",
  EPLAS: "Egeplast",
  ERBOS: "Erbosan",
  ERCB: "Erciyas Çelik Boru",
  EREGL: "Ereğli Demir Çelik",
  ERSU: "Ersu Meyve",
  ESCAR: "Escar Turizm",
  ESCOM: "Escort Teknoloji",
  ESEN: "Esenboğa Elektrik",
  ETILR: "Etiler Gıda",
  ETYAT: "Euro Trend Yatırım",
  EUHOL: "Euro Yatırım Holding",
  EUKYO: "Euro Kapital YO",
  EUPWR: "Europower Enerji",
  EUREN: "Euro Menkul Yatırım",
  EYGYO: "Eyg Gayrimenkul YO",
  FADE: "Fade Gıda",
  FENER: "Fenerbahçe Futbol",
  FLAP: "Flap Kongre Toplantı",
  FMIZP: "Föy Menkul",
  FONET: "Fonet Bilgi Teknolojileri",
  FORMT: "Format Matbaacılık",
  FORTE: "Forte Bilgi İletişim",
  FRIGO: "Frigo Pak Gıda",
  FROTO: "Ford Otosan",
  FZLGY: "Fzl Gayrimenkul",
  GARAN: "Garanti BBVA",
  GARFA: "Garanti Faktoring",
  GEDIK: "Gedik Yatırım Menkul",
  GEDZA: "Gediz Ambalaj",
  GENIL: "Gen İlaç ve Sağlık",
  GENTS: "Gentaş",
  GEREL: "Gersan Elektrik",
  GESAN: "Girişim Elektrik",
  GLBMD: "Global Menkul Değerler",
  GLCVY: "Gelecek Varlık Yönetim",
  GLRYH: "Güler Yatırım Holding",
  GLYHO: "Global Yatırım Holding",
  GMTAS: "Gimat Mağazacılık",
  GOKNR: "Göknur Gıda",
  GOLTS: "Göltaş Çimento",
  GOODY: "Good-Year",
  GOZDE: "Gözde Girişim",
  GRNYO: "Garanti Yatırım Ortaklığı",
  GRSEL: "Gürsel Turizm",
  GRTRK: "Gürtrak",
  GSDDE: "GSD Denizcilik",
  GSDHO: "GSD Holding",
  GSRAY: "Galatasaray Sportif",
  GUBRF: "Gübre Fabrikaları",
  GUNDG: "Günder Enerji",
  GWIND: "Galata Wind Enerji",
  GZNMI: "Gezinomi Seyahat",
  HALKB: "Halkbank",
  HATEK: "Hateks Hatay Tekstil",
  HATSN: "Hatsan Silah",
  HDFGS: "Hedef Girişim",
  HEDEF: "Hedef Holding",
  HEKTS: "Hektaş",
  HKTM: "Hidropar Hareket Kontrol",
  HLGYO: "Halk GYO",
  HOROZ: "Horoz Lojistik",
  HRKET: "Hareket Proje Taşımacılığı",
  HTTBT: "Hitit Bilgisayar",
  HUBVC: "Hub Girişim Sermayesi",
  HUNER: "Hun Yenilenebilir Enerji",
  HURGZ: "Hürriyet Gazetecilik",
  ICBCT: "ICBC Turkey Bank",
  ICUGS: "İçtaş Enerji Üretim",
  IDGYO: "İdealist Gayrimenkul YO",
  IEYHO: "Işıklar Enerji Yapı Holding",
  IHAAS: "İhlas Haber Ajansı",
  IHEVA: "İhlas Ev Aletleri",
  IHGZT: "İhlas Gazetecilik",
  IHLAS: "İhlas Holding",
  IHLGM: "İhlas Gayrimenkul",
  IHYAY: "İhlas Yayın Holding",
  IMASM: "İmaş Makine",
  INDES: "İndeks Bilgisayar",
  INFO: "İnfo Yatırım Menkul",
  INGRM: "İngram Micro",
  INTEM: "İntema İnşaat",
  INVEO: "Inveo Yatırım Holding",
  INVES: "İnvest Yatırım",
  IPEKE: "İpek Doğal Enerji",
  ISATR: "İş Bankası (A)",
  ISBIR: "İşbir Holding",
  ISBTR: "İş Bankası (B)",
  ISCTR: "İş Bankası (C)",
  ISDMR: "İskenderun Demir Çelik",
  ISFIN: "İş Finansal Kiralama",
  ISGSY: "İş Girişim Sermayesi",
  ISGYO: "İş GYO",
  ISKPL: "Işıklar Kimya",
  ISMEN: "İş Yatırım Menkul",
  ISSEN: "İşbir Sentetik",
  ISYAT: "İş Yatırım Ortaklığı",
  IZENR: "İzdemir Enerji",
  IZFAS: "İzmir Fırça",
  IZINV: "İz Yatırım Holding",
  IZMDC: "İzmir Demir Çelik",
  JANTS: "Jantsa Jant",
  KAPLM: "Kaplamin Ambalaj",
  KAREL: "Karel Elektronik",
  KARSN: "Karsan Otomotiv",
  KARTN: "Kartonsan",
  KARYE: "Kartaltepe Mensucat",
  KATMR: "Katmerciler",
  KAYSE: "Kayseri Şeker",
  KBORU: "Kuzey Boru",
  KCAER: "Kocaer Çelik",
  KCHOL: "Koç Holding",
  KENT: "Kent Gıda",
  KERVN: "Kervansaray Yatırım",
  KERVT: "Kerevitaş Gıda",
  KFEIN: "Kafein Yazılım",
  KGYO: "Körfez Gayrimenkul YO",
  KIMMR: "Kim Mağazacılık",
  KLGYO: "Kiler Gayrimenkul YO",
  KLKIM: "Kalekim Kimyevi",
  KLMSN: "Klimasan Klima",
  KLNMA: "Kalkınma Yatırım Bankası",
  KLRHO: "Kiler Holding",
  KLSER: "Kaleseramik",
  KLSYN: "Kaleseramik Sanayi",
  KMPUR: "Kimpur Kimya",
  KNFRT: "Konfrut Gıda",
  KONKA: "Konya Kağıt",
  KONTR: "Kontrolmatik Teknoloji",
  KONYA: "Konya Çimento",
  KOPOL: "Koroplast",
  KORDS: "Kordsa Teknik Tekstil",
  KOTON: "Koton Mağazacılık",
  KOZAA: "Koza Anadolu Metal",
  KOZAL: "Koza Altın",
  KRDMA: "Kardemir (A)",
  KRDMB: "Kardemir (B)",
  KRDMD: "Kardemir (D)",
  KRGYO: "Körfez GYO",
  KRONT: "Kron Telekomünikasyon",
  KRPLS: "Karel Plastik",
  KRSTL: "Kristal Kola",
  KRTEK: "Karsu Tekstil",
  KRVGD: "Kervan Gıda",
  KSTUR: "Kuştur Kuşadası Turizm",
  KTLEV: "Katılımevim Tasarruf",
  KTSKR: "Kütahya Şeker",
  KUTPO: "Kütahya Porselen",
  KUYAS: "Kuyaş Yatırım",
  KZBGY: "Kızılbük GYO",
  KZGYO: "Kızılırmak GYO",
  LIDER: "Lider Faktoring",
  LIDFA: "Lider Faktoring Hizmetleri",
  LILAK: "Lila Kağıt",
  LINK: "Link Bilgisayar",
  LKMNH: "Lokman Hekim Sağlık",
  LMKDC: "Limak Doğu Anadolu Çimento",
  LOGO: "Logo Yazılım",
  LRSHO: "Lares Menkul",
  LUKSK: "Lüks Kadife",
  MAALT: "Marmaris Altınyunus",
  MACKO: "Macko Metal",
  MAGEN: "Margün Enerji",
  MAKIM: "Makim Makine",
  MAKTK: "Makina Takım",
  MANAS: "Manas Enerji",
  MARBL: "Marbil Bilişim",
  MARKA: "Marka Yatırım Holding",
  MARTI: "Martı Otel",
  MAVI: "Mavi Giyim",
  MEDTR: "Meditera Tıbbi Malzeme",
  MEGAP: "Mega Polietilen",
  MEGMT: "Mega Metal",
  MEKAG: "Meka Global",
  MEPET: "Mepet Metro Petrol",
  MERCN: "Mercan Kimya",
  MERIT: "Merit Turizm",
  MERKO: "Merko Gıda",
  METRO: "Metro Ticari Holding",
  METUR: "Metemtur Otel",
  MGROS: "Migros Ticaret",
  MHRGY: "Mahir Gayrimenkul",
  MIATK: "Mia Teknoloji",
  MIPAZ: "Milpa",
  MMCAS: "MMC Sanayi",
  MNDRS: "Menderes Tekstil",
  MNDTR: "Mondi Tire Kutsan",
  MOBTL: "Mobiltel İletişim",
  MOGAN: "Mogan Enerji",
  MPARK: "MLP Sağlık (Medical Park)",
  MRGYO: "Martı Gayrimenkul YO",
  MRSHL: "Marshall",
  MSGYO: "Mistral Gayrimenkul YO",
  MTRKS: "Matriks Bilgi Dağıtım",
  MTRYO: "Metro Yatırım Ortaklığı",
  MZHLD: "Mazhar Zorlu Holding",
  NATEN: "Naturel Yenilenebilir Enerji",
  NETAS: "Netaş Telekomünikasyon",
  NIBAS: "Niğbaş Niğde Beton",
  NTGAZ: "Naturelgaz",
  NTHOL: "Net Holding",
  NUGYO: "Nurol Gayrimenkul YO",
  NUHCM: "Nuh Çimento",
  OBAMS: "Oba Makarna",
  OBASE: "Obase Bilgisayar",
  ODAS: "Odaş Elektrik",
  ODINE: "Odine Solutions",
  OFSYM: "Ofis Yem Gıda",
  ONCSM: "Oncosem Onkolojik",
  ONRYT: "Onur Yüksek Teknoloji",
  ORCAY: "Orçay Ortaköy Çay",
  ORGE: "Orge Enerji Elektrik",
  ORMA: "Orma Orman Mahsulleri",
  OSMEN: "Osmanlı Menkul Değerler",
  OSTIM: "Ostim Endüstriyel Yatırımlar",
  OTKAR: "Otokar",
  OTTO: "Otto Holding",
  OYAKC: "Oyak Çimento",
  OYLUM: "Oylum Sınai Yatırımlar",
  OYYAT: "Oyak Yatırım Ortaklığı",
  OZGYO: "Özderici Gayrimenkul YO",
  OZKGY: "Özak Gayrimenkul YO",
  OZRDN: "Özerden Plastik",
  OZSUB: "Özsu Balık",
  PAGYO: "Panora Gayrimenkul YO",
  PAMEL: "Pamel Yenilenebilir Elektrik",
  PAPIL: "Papilon Savunma",
  PARSN: "Parsan",
  PASEU: "Pasifik Eurasia Lojistik",
  PATEK: "Pat Enerji",
  PCILT: "PC İletişim Medya",
  PEHOL: "Pergamon Holding",
  PEKGY: "Peker Gayrimenkul YO",
  PENGD: "Penguen Gıda",
  PENTA: "Penta Teknoloji",
  PETKM: "Petkim",
  PETUN: "Pınar Et ve Un",
  PGSUS: "Pegasus",
  PINSU: "Pınar Su ve İçecek",
  PKART: "Plastikkart",
  PKENT: "Petrokent Turizm",
  PLTUR: "Platform Turizm",
  PNLSN: "Panelsan Çatı Cephe",
  PNSUT: "Pınar Süt",
  POLHO: "Polisan Holding",
  POLTK: "Politeknik Metal",
  PRDGS: "Pardus Girişim",
  PRKAB: "Türk Prysmian Kablo",
  PRKME: "Park Elektrik Madencilik",
  PRZMA: "Prizma Press Matbaacılık",
  PSDTC: "Pesa Dış Ticaret",
  PSGYO: "Pera Gayrimenkul YO",
  QUAGR: "QUA Granite",
  RALYH: "Ral Yatırım Holding",
  RAYSG: "Ray Sigorta",
  REEDR: "Reeder Teknoloji",
  RGYAS: "Rönesans Gayrimenkul",
  RNPOL: "Rainbow Polikarbonat",
  RODRG: "Rodrigo Tekstil",
  ROYAL: "Royal Halı",
  RTALB: "RTA Laboratuvarları",
  RUBNS: "Rubenis Tekstil",
  RYGYO: "Reysaş Gayrimenkul YO",
  RYSAS: "Reysaş Taşımacılık",
  SAFKR: "Şafak Yapı",
  SAHOL: "Sabancı Holding",
  SAMAT: "Saray Matbaacılık",
  SANEL: "Sanel Mühendislik",
  SANFM: "Sanifoam Sünger",
  SANKO: "Sanko Pazarlama",
  SARKY: "Sarkuysan",
  SASA: "Sasa Polyester",
  SAYAS: "Say Reklamcılık",
  SDTTR: "SDT Uzay ve Savunma",
  SEGYO: "Semih Gayrimenkul YO",
  SEKFK: "Şeker Finansal Kiralama",
  SEKUR: "Sekuro Plastik",
  SELEC: "Selçuk Ecza Deposu",
  SELGD: "Selçuk Gıda",
  SELVA: "Selva Gıda",
  SERVE: "Serve Kırtasiye",
  SEYKM: "Seyitler Kimya",
  SILVR: "Silverline Endüstri",
  SISE: "Şişe Cam",
  SKBNK: "Şekerbank",
  SKTAS: "Söktaş Tekstil",
  SKYLP: "Seyitler Kimya (SKYLP)",
  SKYMD: "Gelecek Varlık",
  SMART: "Smart Güneş Enerjisi",
  SMRTG: "Smart Güneş Teknolojileri",
  SNGYO: "Sinpaş Gayrimenkul YO",
  SNICA: "Sanica Isı",
  SNKRN: "Senkron Güvenlik",
  SNPAM: "Sönmez Pamuklu",
  SODSN: "Sodaş Sodyum",
  SOKE: "Söke Değirmencilik",
  SOKM: "Şok Marketler",
  SONME: "Sönmez Filament",
  SRVGY: "Servet Gayrimenkul YO",
  SUMAS: "Sun Tekstil",
  SUNTK: "Sun Tekstil",
  SURGY: "Sur Gayrimenkul YO",
  SUWEN: "Suwen Tekstil",
  TABGD: "TAB Gıda",
  TARKM: "Tarım Kredi Kimya",
  TATEN: "Tatlıpınar Enerji",
  TATGD: "Tat Gıda",
  TAVHL: "TAV Havalimanları",
  TBORG: "Türk Tuborg",
  TCELL: "Turkcell",
  TDGYO: "Trend Gayrimenkul YO",
  TEKTU: "Tek-Art Turizm",
  TERA: "Tera Yatırım Menkul",
  TETMT: "Tetamat Gıda",
  TEZOL: "Tezol Enerji",
  TGSAS: "TGS Dış Ticaret",
  THYAO: "Türk Hava Yolları",
  TKFEN: "Tekfen Holding",
  TKNSA: "Teknosa",
  TLMAN: "Trabzon Liman İşletmeciliği",
  TMPOL: "Temapol Polimer",
  TMSN: "Tümosan Motor",
  TNZTP: "Tanrıverdi Tekstil",
  TOASO: "Tofaş Otomobil",
  TRCAS: "Turcas Petrol",
  TRGYO: "Torunlar Gayrimenkul YO",
  TRILC: "Türk İlaç Serum",
  TSGYO: "TSKB Gayrimenkul YO",
  TSKB: "TSKB",
  TSPOR: "Trabzonspor Sportif",
  TTKOM: "Türk Telekom",
  TTRAK: "Türk Traktör",
  TUCLK: "Tuğçelik Alüminyum",
  TUKAS: "Tukaş",
  TUPRS: "Tüpraş",
  TUREX: "Tureks Turizm Taşımacılık",
  TURGG: "Türker Proje Gayrimenkul",
  TURSG: "Türkiye Sigorta",
  UFUK: "Ufuk Yatırım",
  ULAS: "Ulaşlar Turizm",
  ULKER: "Ülker Bisküvi",
  ULUFA: "Ulufa Faktoring",
  ULUSE: "Ulusoy Elektrik",
  ULUUN: "Ulusoy Un",
  UMPAS: "Umpaş Holding",
  UNLU: "Ünlü Yatırım Holding",
  USAK: "Uşak Seramik",
  UZERB: "Uzertaş Boya",
  VAKBN: "Vakıfbank",
  VAKFN: "Vakıf Finansal Kiralama",
  VAKKO: "Vakko Tekstil",
  VANGD: "Vanet Gıda",
  VBTYZ: "VBT Yazılım",
  VERTU: "Verusaturk Girişim",
  VERUS: "Verusa Holding",
  VESBE: "Vestel Beyaz Eşya",
  VESTL: "Vestel Elektronik",
  VKGYO: "Vakıf Gayrimenkul YO",
  VKING: "Viking Kağıt",
  VRGYO: "Vera Gayrimenkul YO",
  YAPRK: "Yaprak Süt",
  YATAS: "Yataş",
  YAYLA: "Yayla Enerji",
  YBTAS: "Yaylı Boru",
  YEOTK: "Yeo Teknoloji Enerji",
  YESIL: "Yeşil Yatırım Holding",
  YGGYO: "YG Gayrimenkul YO",
  YGYO: "Yeşil Gayrimenkul YO",
  YIGIT: "Yiğit Akü",
  YKBNK: "Yapı Kredi Bankası",
  YKSLN: "Yükselen Çelik",
  YONGA: "Yonga Mobilya",
  YUNSA: "Yünsa",
  YYAPI: "Yeşil Yapı",
  YYLGD: "Yayla Agro Gıda",
  ZEDUR: "Zedur Enerji",
  ZOREN: "Zorlu Enerji",
  ZRGYO: "Ziraat Gayrimenkul YO",
}
